version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: mongo
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8083:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  backend:
    hostname: sahtian-backend
    image: sahtian-backend:dev
    command: sh -c "/app/sahtian-backend serve"
    ports:
      - "9080:8080"

volumes:
  dbdata6: